# Generated by Django 6.0.1 on 2026-01-16 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price_without_jewelry', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_with_jewelry', models.DecimalField(decimal_places=2, max_digits=10)),
                ('security_deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DressImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='dresses/')),
                ('dress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rentals.dress')),
            ],
        ),
        migrations.CreateModel(
            name='DressRentalPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('note', models.CharField(blank=True, max_length=255)),
                ('dress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_periods', to='rentals.dress')),
            ],
        ),
    ]
