# Generated by Django 6.0.1 on 2026-01-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dressimage',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
