# Generated by Django 6.0.1 on 2026-01-18 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_dressimage_is_primary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dressrentalperiod',
            name='note',
        ),
        migrations.AddField(
            model_name='dress',
            name='dress_type',
            field=models.CharField(choices=[('saree', 'Saree'), ('lehenga', 'Lehenga'), ('sharara', 'Sharara'), ('gown', 'Gown'), ('anarkali', 'Anarkali'), ('indo_western', 'Indo-Western')], default='saree', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dress',
            name='sizes',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='dress',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('rented', 'Rented'), ('maintenance', 'Maintenance')], default='available', max_length=20),
        ),
    ]
