# Generated by Django 6.0.1 on 2026-01-18 10:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_remove_dressrentalperiod_note_dress_dress_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dressimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
