# Generated by Django 4.2.7 on 2026-02-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_alter_dressimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dressrentalperiod',
            name='renter_contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dressrentalperiod',
            name='renter_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dress',
            name='dress_type',
            field=models.CharField(choices=[('saree', 'Saree'), ('lehenga', 'Lehenga'), ('bridal_lehenga', 'Bridal Lehenga'), ('sharara', 'Sharara'), ('gown', 'Gown'), ('anarkali', 'Anarkali'), ('indo_western', 'Indo-Western'), ('kurta_set', 'Kurta Set')], max_length=50),
        ),
    ]
