# Generated by Django 4.2.7 on 2026-02-25 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0005_dressrentalperiod_renter_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dress',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='dress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='dress',
            name='dress_type',
            field=models.CharField(choices=[('saree', 'Saree'), ('lehenga', 'Lehenga'), ('bridal_lehenga', 'Bridal Lehenga'), ('sharara', 'Sharara'), ('gown', 'Gown'), ('anarkali', 'Anarkali'), ('indo_western', 'Indo-Western'), ('kurta_set', 'Kurta Set')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dress',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='dress',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='dress',
            name='price_without_jewelry',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dress',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('rented', 'Rented'), ('maintenance', 'Maintenance')], db_index=True, default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='dressimage',
            name='is_primary',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='dress',
            index=models.Index(fields=['dress_type', 'is_active'], name='rentals_dre_dress_t_320887_idx'),
        ),
        migrations.AddIndex(
            model_name='dress',
            index=models.Index(fields=['is_featured', 'is_active'], name='rentals_dre_is_feat_81ae3a_idx'),
        ),
        migrations.AddIndex(
            model_name='dress',
            index=models.Index(fields=['price_without_jewelry'], name='rentals_dre_price_w_11d625_idx'),
        ),
        migrations.AddIndex(
            model_name='dressrentalperiod',
            index=models.Index(fields=['dress', 'start_date', 'end_date'], name='rentals_dre_dress_i_2efbfe_idx'),
        ),
    ]
